EgBoxLayout:

	
			
<MainWidget>:
	Button:
		text:"HELLO"
		size:"50dp","30dp"
		pos:"100dp","200dp"
		
	Label:
		text:"Label"
		size:"50dp","30dp"
		pos:"200dp","300dp"
		color:1,0,0,0.5
		
<EgBoxLayout>:
	#orientation:"horiz"
	Button:
		text:"A"
#		size_hint:0.5,None
	#	height:"700dp"
	##	pos_hint:{"center_y":0.5}
		

	BoxLayout:
		orientation:"vertical"
		spacing:"10dp"
		Button:
			text:"C"
		Button:
			text:"D"
		Button:
			text:"E"
		
	
	Button:
		text:"D"
		